# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"print_hello": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://dharmeshkakadia.github.io/nbdev_playground/"

git_url = "https://github.com/dharmeshkakadia/nbdev_playground/tree/master/"

def custom_doc_links(name): return None
